### ISSUE TITLE
Window Size

### ISSUE THREAD

**Issue by MiguelNiblock** [morpheusthewhite/nordpy#11]
Hi! Thanks for building this awesome utility. I was hating Openvpn until I found it. Everything works actually. 

**Only comment** is that everytime I run Nordpy I need to resize the window because nothing is visible. Same happens with the pop out windows for choosing server manually. I must resize it in order to see the list, and the OK button below.

Im not sure if this is actually due to my system. Im running Mint 19.1
Anyway, here's a screenshot so you get an idea.

![image](https://user-images.githubusercontent.com/32658920/51286934-16d98680-19aa-11e9-90c3-99dbb5555a4b.png)

**Comment by morpheusthewhite** [comment]
It's probably caused by your default font size; I'll soon try to save also the size of the window, so that it will be restored at each start

**Comment by morpheusthewhite** [comment]
Please run this code by pasting in a python file and launching it and post the output

`
from tkinter import Label, font

l = Label(text='foo')
fo = font.Font(l, l.cget('font'))
print(fo.actual())
`

**Comment by morpheusthewhite** [comment]
Solved with the use of the scale factor in the advanced settings

**Comment by foxmajik** [comment]
This is not a good user experience.

Most people who want a GUI for their VPN connection are not going to understand what a "scale factor" is.

You should just use better UI code (get the font size from the OS using your code and size the window) instead of expecting the user to know what is going on and fix it themselves.

**Comment by morpheusthewhite** [comment]
> This is not a good user experience.
> 
> Most people who want a GUI for their VPN connection are not going to understand what a "scale factor" is.
> 
> You should just use better UI code (get the font size from the OS using your code and size the window) instead of expecting the user to know what is going on and fix it themselves.

You're totally right
