### ISSUE TITLE
automatic connect freezes

### ISSUE THREAD

**Issue by janat08** [morpheusthewhite/NordPy#12]
Ubuntu 18.04 distro kde neon will freeze.

**Comment by morpheusthewhite** [comment]
Can you launch it from terminal and paste here the output?

**Comment by morpheusthewhite** [comment]
probably solved by https://github.com/morpheusthewhite/NordPy/commit/dafc49d06aff98a09ecef655f843d8c79c610921, you can switch to the other unstable branch (soon will be stable and merged to the master)

**Comment by morpheusthewhite** [comment]
try pulling from the master the latest release

**Comment by janat08** [comment]
``
resulting url: https://nordvpn.com/wp-admin/admin-ajax.php?action=servers_recommendations&filters={%22servers_groups%22:11}
``
no connection available, please reconnect and try again. it didn't ask for user/pass.

**Comment by janat08** [comment]
btw there're snaps and flatpak distributions.

**Comment by janat08** [comment]
Yes, the cli works though

**Comment by morpheusthewhite** [comment]
I mean, a pop up saying "no connection available, please reconnect and try again" is shown, then the gui becomes available again. 

Am I wrong?

**Comment by janat08** [comment]
No youre not.

**Comment by morpheusthewhite** [comment]
I just pushed on the master, pull and try to connect now. Let me know what happens

**Comment by janat08** [comment]
Still gives me the same message. nordvpn.com is blocked for me, do you depend on making calls to them- the cli works though?

**Comment by morpheusthewhite** [comment]
Can you reach NordVPN from a browser?

**Comment by janat08** [comment]
no, the extension works though.
