### ISSUE TITLE
DNS leak

### ISSUE THREAD

**Issue by mexicanhaze** [morpheusthewhite/NordPy#14]
It seems there are DNS leaks when using the app.

**Comment by morpheusthewhite** [comment]
Can you post your configuration? This may be caused by already known vulnerabilities in the [Network Manager](https://bugs.launchpad.net/ubuntu/+source/network-manager-openvpn/+bug/1690759)

**Comment by morpheusthewhite** [comment]
If Network Manager is checked in the advanced configuration window you can easily disable it

**Comment by morpheusthewhite** [comment]
Further studies I've just made show also openvpn command line client leaks DNS. The last commit should fix it

**Comment by mexicanhaze** [comment]
I disabled NetworkManager in the advanced configuration but the DNS still leaks. You asked to post my configuration, what did you mean by it and where can I get the info you want?
I''l try the las commit and keep you posted

**Comment by mexicanhaze** [comment]
The last commit works splendidly. I disabled Networkmanager as suggested and no DNS leak any more.
Thank you very much for the quick response and solution as well as the app

**Comment by morpheusthewhite** [comment]
Thank you for the great feedback!
