### ISSUE TITLE
Missing theme for application

### ISSUE THREAD

**Issue by coreybruce** [morpheusthewhite/NordPy#15]
Not sure if this is using GTK or Qt but the application has no theme for me

https://imgur.com/1UOHRDB.png

**Comment by morpheusthewhite** [comment]
It's tkinter, a python library for GUIs; it's rendered in its own style, disregarding the environment, but it inherits the colors from your theme.
So the screenshots i posted are mainly rendered dark because I use a dark color in my environment (KDE Plasma)
