### ISSUE TITLE
NordVPN Xor servers

### ISSUE THREAD

**Issue by XOR-p** [morpheusthewhite/NordPy#16]
Can you add support for Xor servers? I bet “scramble obfuscate” in ovpn config will not work.

**Comment by morpheusthewhite** [comment]
I'll work on it, it seems to be quite simple using obfsproxy

**Comment by morpheusthewhite** [comment]
According to [nordvpn.com](https://support.nordvpn.com/General-info/Features/1047407962/What-do-the-different-server-categories-mean.htm)
>This category [obfuscated] is available only on our OpenVPN apps: Windows, Android, Linux and the OpenVPN version for macOS.

so NordPy cannot use those server, since NordVPN (that's really bad) doesn't provide .ovpn for those servers

**Comment by XOR-p** [comment]
https://downloads.nordwebsite.net/configs/archives/servers/ovpn_xor.zip 
click!

**Comment by morpheusthewhite** [comment]
That's great! Thank you, I'll restart working

**Comment by morpheusthewhite** [comment]
Now available on `master`
