### ISSUE TITLE
Excluding certain Apps

### ISSUE THREAD

**Issue by DonnyDope** [morpheusthewhite/nordpy#21]
Hi, first of all, great project! Thanks for taking the time. 

I have just created myself a NORDVPN account. I knew beforehand that they only have a terminal app for Linux. However, I didn't know it's functionality is so limited. 

I would like to be able to exclude certain apps from the VPN connection, since there are services which don't allow IP proxying.

I'm quite experienced in programming with Python. I would love to contribute something to implementing this feature. However, my experience with Linux is very limited. I wouldn't know where to start. Could you give me some directions?

**Comment by morpheusthewhite** [comment]
Since I didn't know how to solve such a problem, after some search I found [here](https://superuser.com/questions/294008/use-vpn-connection-only-for-selected-applications) an answer which explains how to accomplish that.

If you want to contribute directly (by creating a PR) it would be great!

**Comment by DonnyDope** [comment]
I've also done some research, and it seems that it will take me quite some time to figure it out. I will get back to you as soon, as I have managed to implement a solution. Once it works, we can start thinking about how to implement it in Python, and add it to your project.

**Comment by morpheusthewhite** [comment]
Ok, let me know!

**Comment by morpheusthewhite** [comment]
Closing as staled
