### ISSUE TITLE
No auto-connection at startup

### ISSUE THREAD

**Issue by mouarfff** [morpheusthewhite/nordpy#24]
hello thx for this app !

(nordvpn don't care of linux users)

So, i can't manage any autoconnection at startup :
first i need to type root password (root ? no sudo/sudoer ?),
i need to choose my location and number of server, and clic ok, and after clic to connect 

is't possible to memeory this, and/or select some server we want to connect automaticaly ?

thx

**Comment by morpheusthewhite** [comment]
Yeah of course, It actually does save the last type of server you choose, the country and the protocol, but you need to type the sudo password each time (yeah, sudoers).

**Comment by mouarfff** [comment]
ok but if i alway need to ask for root passwd and can't use sudoer it's an issue

**Comment by morpheusthewhite** [comment]
You can use sudoers

**Comment by mouarfff** [comment]
I know, but it doesn't work with py script ..

and normally, this apply should have this possibility ?

**Comment by morpheusthewhite** [comment]
What do you mean? Do you want to control nordpy from outer scripts in order to connect automatically to the last used server?

**Comment by mouarfff** [comment]
I just want launch nordpy at startup easy, without ask for root passwd/sudo, and conect automatically in network i choosen (as i can do in the windows app)

So i added nordpy in sudoers but it doesn't work. I do this for another programms and it's ok but nordpy not

**Comment by morpheusthewhite** [comment]
So you want that at the start of the system nordpy automatically connects to the last server, without opening the application or providing the sudo password to it. Am I right?

**Comment by mouarfff** [comment]
in windows, the app can autostart at session login startup AND connect automatically the last best used network WITHOUT any password and clic or anything else.

**Comment by morpheusthewhite** [comment]
Good, I'll work on a solution for it

**Comment by morpheusthewhite** [comment]
Now it is possible to setup autostart, just follow the instructions you can find [here](https://github.com/morpheusthewhite/nordpy/blob/master/README.md#autostart) (remember to update nordpy)

**Comment by mouarfff** [comment]
but i will not have the gui open when desktop start ?

**Comment by mouarfff** [comment]
it doesn't work. (linux mint mate 19)

and with this method, if i want to have the gui openned at startup of my desktop session, i have alway invited to type root password ... (mmm sudo passwd instead)

**Comment by morpheusthewhite** [comment]
It starts in the background, no gui is opened.

And yes, whenever you open it you will need to type the password
