### ISSUE TITLE
Scripts do not have executable bit set

### ISSUE THREAD

**Issue by foxmajik** [morpheusthewhite/nordpy#30]
In the most recent version as of the posting of this issue:

Scripts do not have execute bit set, but they are called like executables.

So when you try to do that the OS reports that the program is not found.

You need to either call the scripts as a switch to the Python executable or set the executable bit during install.

**Comment by morpheusthewhite** [comment]
What specific script are you referring to?

For me both `nordpy.py` and all the `.sh` in the `scripts` folder are executable
