### ISSUE TITLE
Whitelist SSH on LAN

### ISSUE THREAD

**Issue by MountainX** [morpheusthewhite/nordpy#37]
**Describe the question**
Is it possible to allow other devices on the local area network to connect with SSH to the computer running NordPy while VPN is active?

**Expected behavior**
I am hoping for a whitelist option for subnetwork and port to allow local SSH connections while the VPN is active

**Desktop (please complete the following information):**
 - Linux Distribution: Arch Linux
 - NordPy version: latest

**Additional context**
The official NordVPN app for Linux is supposed to allow this feature, but it is currently not working correctly. I'm using the opportunity to find another app, and this looks like a good one.

**Comment by morpheusthewhite** [comment]
This should be easily feasible through an additional rule in the killswitch script

**Comment by MountainX** [comment]
> This should be easily feasible through an additional rule in the killswitch script

I will be happy to do testing.

**Comment by morpheusthewhite** [comment]
Well actually it should work without changes. Did you try?

**Comment by MountainX** [comment]
> Well actually it should work without changes. Did you try?

Do you mean did I try adding a additional rule in the killswitch script? I would like to, but I am not sure which rule to add. Can you suggest the rule that is needed? Thanks.

**Comment by MountainX** [comment]
Maybe these rules? (Assuming my LAN subnet is 192.168.0.1/24 and SSH port is 22)

iptables -A INPUT -p tcp -m state --state NEW --source 192.168.0.1/24 --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -j DROP

Where should they be added? Would it be at line 39 of https://github.com/morpheusthewhite/nordpy/blob/master/scripts/ip-ks.sh

**Comment by morpheusthewhite** [comment]
> So, looking at [ip-ks.sh ](https://github.com/morpheusthewhite/nordpy/blob/master/scripts/ip-ks.sh)again, I see these rules:
> 
> iptables -A INPUT --src $NETWORK_ADDRESS -j ACCEPT -i $INTERFACE
> iptables -A OUTPUT -d $NETWORK_ADDRESS -j ACCEPT -o $INTERFACE
> 
> In this case, is `$NETWORK_ADDRESS` the subnet of my LAN? If so, then I can see that it should work. If you confirm my guess, I will proceed to verify by testing.

Exactly
