### ISSUE TITLE
Inconvenient centering with multiple displays

### ISSUE THREAD

**Issue by emulti** [morpheusthewhite/nordpy#38]
When using nordpy with multiple monitors, the 'centering' code uses the dimensions of the extended desktop rather than (I suggest) 'screen 1', giving an odd position on setups with differently-sized displays.

**Expected behavior**
nordpy window opens at centre of one of the screens

**Actual behaviour**
nordpy opens at centre of extended desktop

**Desktop (please complete the following information):**
 - Arch Linux
 - aur/nordpy 1.3.3-1

Very nice application, a lightweight alternative to the "official" nordvpn binary that doesn't use 200MB of memory.

**Comment by emulti** [comment]
The font scaling behaviour with multiple displays could also be improved.
Gnome/Xorg: Fonts appear very tiny unless only one display connected. Probably because dimensions of extended desktop are used in calculating the font size. If only one display connected the behaviour is perfect.

Gnome/Wayland (+ XWayland)
Multiple displays: Fonts are slightly larger than normal
Single display: normal behaviour.

**Comment by morpheusthewhite** [comment]
> The font scaling behaviour with multiple displays could also be improved.
> Gnome/Xorg: Fonts appear very tiny unless only one display connected. Probably because dimensions of extended desktop are used in calculating the font size. If only one display connected the behaviour is perfect.

That's strange since the actual size of the font is unchanged in the application, it completely relies on the `tkinter` library in that sense.

**Comment by emulti** [comment]
Font size under Wayland is the same with both single/multiple screens.

Under Xorg, single screen: 
![xorg_single screen](https://user-images.githubusercontent.com/7505390/78990442-5a2f9000-7b2e-11ea-90bd-9464ea00c6c0.png)

Xorg, two screens: 
![xorg_two screens](https://user-images.githubusercontent.com/7505390/78990480-6fa4ba00-7b2e-11ea-9654-24a6bc8839eb.png)

Obviously the centering of the window (which uses `self.winfo_screenwidth()`) is a separate issue

**Comment by morpheusthewhite** [comment]
I created a new issue to reference this last problem

**Comment by emulti** [comment]
Correct, having solved #40 the issue is confined to the centering on startup only.

**Comment by morpheusthewhite** [comment]
Just installing `screeninfo` (`pip3 install screeninfo`) will fix the centering
