### ISSUE TITLE
Can't add nordpy to 'Favorites' in Gnome Dash

### ISSUE THREAD

**Issue by emulti** [morpheusthewhite/nordpy#39]
nordpy under Gnome can't be added to 'favorites' in Dash by right-clicking and selecting 'add to favorites'
If added forcibly (by dragging icon in overview manually to Dock or using dconf-editor) then a running instance of nordpy shows as a second item in the Dash

**To Reproduce**
Run nordpy from 'Applications overview' in the normal Gnome manner
Right-click of Dash icon does not have 'add to favorites' in context menu

**Expected behavior**
Should be possible to 'add to favourites'. This can be done by dragging the icon in the applications overview into Dash, but on next run a second application icon appears when running.

**Assumed Cause**
Application does not declare StartupWMClass correctly

**Workaround**
$ cp /usr/share/applications/nordpy.desktop .local/share/applications
Edit .local/share/applications/nordpy.desktop and add the following line: 
StartupWMClass=tk

Second icon is not now shwon when running and the correct context menu appears on right-click

**Desktop (please complete the following information):**
 - Arch Linux/Gnome
 - NordPy 1.3.3-1

**Comment by morpheusthewhite** [comment]
It shouldn't be necessary to move the entry into the user folder; try now

**Comment by emulti** [comment]
yes, that works.
