### ISSUE TITLE
*Feature Request* Bypass VPN DNS

### ISSUE THREAD

**Issue by Fzndox** [morpheusthewhite/nordpy#43]
This would be ideal if there was an option to disable/ignore the VPN DNS. 
In windows I would typically download specific ovpn files and edit them to ignore the DNS in some cases.

Would a toggle be possible for this?

I'm under the latest arch as of 4/29/20 using nordpy 1.3.3-1.

**Comment by morpheusthewhite** [comment]
Beware: this will mean leaking DNS

**Comment by morpheusthewhite** [comment]
It the request is toggle between using NordVPN DNS and system default DNS that is not actually possible, I experienced many resolution problem when NordPy was not manually setting the DNS
