### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'iptables-legacy': 

### ISSUE THREAD

**Issue by nvkreg** [morpheusthewhite/nordpy#53]
Hi 
I'm getting an error message when trying to run nordpy.  I get the password prompt, but then the following message.

I have reinstalled and rebooted.

This is on a clean install of debian buster

user@debian:~/Downloads/nordpy-master$ chmod +x install.sh
user@debian:~/Downloads/nordpy-master$ ./install.sh

Do you want to install support for obfuscated servers (it will reinstall openvpn)?[y/n] (Recommended: n)
n
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openvpn is already the newest version (2.4.7-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Required packages installed
installing certificates (needed by ipsec)
downloading and extracting conf files from NordVPN
user@debian:~/Downloads/nordpy-master$ nordpy
Traceback (most recent call last):
  File "/usr/local/bin/nordpy", line 62, in <module>
    main()
  File "/usr/local/bin/nordpy", line 56, in main
    from bin.gui import gui
  File "/home/user/Downloads/nordpy-master/bin/gui.py", line 10, in <module>
    from bin.vpn_util.vpn import *
  File "/home/user/Downloads/nordpy-master/bin/vpn_util/vpn.py", line 2, in <module>
    from bin.vpn_util.openvpn import *
  File "/home/user/Downloads/nordpy-master/bin/vpn_util/openvpn.py", line 6, in <module>
    from bin.vpn_util.killswitch import killswitch_up, killswitch_down
  File "/home/user/Downloads/nordpy-master/bin/vpn_util/killswitch.py", line 22, in <module>
    has_legacy = check_has_legacy()
  File "/home/user/Downloads/nordpy-master/bin/vpn_util/killswitch.py", line 15, in check_has_legacy
    universal_newlines=True).communicate()
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'iptables-legacy': 'iptables-legacy'
Retrieved stats
Retrieved stats
user@debian:~/Downloads/nordpy-master$

**Comment by nvkreg** [comment]
extra info:

# Generated by NetworkManager
nameserver 192.168.2.1


ip r
---
default via 192.168.2.1 dev wlp4s0 proto dhcp metric 600 
169.254.0.0/16 dev wlp4s0 scope link metric 1000 
192.168.2.0/24 dev wlp4s0 proto kernel scope link src 192.168.2.88 metric 600 


sudo iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by nvkreg** [comment]
Thanks,  I reinstalled and it works.  however, got a few errors during install

sudo ./install.sh
[sudo] password for user: 
Do you want to install support for obfuscated servers (it will reinstall openvpn)?[y/n] (Recommended: n)
n
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
sudo: dnf: command not found
sudo: pacman: command not found
Your distro is not supported, please follow README
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
Required packages installed
installing certificates (needed by ipsec)
downloading and extracting conf files from NordVPN

**Comment by morpheusthewhite** [comment]
It's a problem with your system, probably `apt` exited abnormally last time you runned it. It will still work
