### ISSUE TITLE
Unnecessary calling of `sudo ipsec status` and `sudo ipsec --version` on Arch...

### ISSUE THREAD

**Issue by n8jadams** [morpheusthewhite/nordpy#54]
I'm on Arch linux with KDE Plasma and I'm using these two repos for the AUR: https://aur.archlinux.org/packages/nordpy/ https://aur.archlinux.org/packages/nordpy-plasmoid-git/

**Describe the bug**
I ran into a weird problem where I would experience a pam faillock because of this app. You can see some back and forth details on [this thread on the Arch linux forums](https://bbs.archlinux.org/viewtopic.php?pid=1997124).

Ultimately, it looks like the following commands get called fairly frequently by nordpy in the background

```
sudo ipsec status
sudo ipsec --version
```

despite the fact that I hadn't installed `strongswan`.

This seemed to cause the pam faillock. When I added a `NOPASSWD: /usr/bin/ipsec` to my user in my sudoers file, the problem went away.

It seems that nord py
* shouldn't call ipsec if `strongswan` isn't installed
* shouldn't call `ipsec status/--version` with sudo at all, and if `sudo` is necessary, then there should be a better way to raise those privileges.

**Desktop (please complete the following information):**
 - Linux Distribution: Linux-Zen kernel, Arch Distro, KDE Plasma
 - NordPy version: 1.3.4

I don't know if other Arch users have run into this or if it's just due to a configuration on my own machine, but hopefully this report is helpful. I really appreciate this GUI and it has a ton of potential for us non-windows/mac users. :)

**Comment by morpheusthewhite** [comment]
Thanks for the report. I didn't experience it, even if I am also on Arch.

If you can try to run the patched version let me know if you continue experiencing the same problem.

**Comment by n8jadams** [comment]
Thanks, that seemed to have fixed it. Will you be making a new version number with this patch?

**Comment by morpheusthewhite** [comment]
I'll do as soon as I correct another problem related to ikev2
