### ISSUE TITLE
Killswitch

### ISSUE THREAD

**Issue by morpheusthewhite** [morpheusthewhite/NordPy#8]
Implement a killswitch

**Comment by corrad1nho** [comment]
One way to approach this is using a firewall that blocks non-VPN connections. I have created a similar project and you can see the rules I'm using in [this](https://github.com/corrad1nho/qomui/blob/master/resources/firewall_default.json) file. The actual script (Python, too) is [here](https://github.com/corrad1nho/qomui/blob/master/qomui/firewall.py). 

Things to consider:
- you'll have to allow the entry-ip of the OpenVPN server, too, if the firewall / killswitch is active before making a connection attempt
- it might make sense to restore flushed rules after closing the app / the connection
- if ipv6 is not needed you can block it entirely

**Comment by morpheusthewhite** [comment]
Thank you, you made my day!
